# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yuanchu (James) Liang
title: PhD Candidate @ The Australian National University
email: yuanchu.liang@anu.edu.au
website: yc-liang.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  YC-Liang
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: yuanchu-liang-89485320b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_pic.JPG
about_content: | # this will include new lines to allow paragraphs
  Nice to meet you! I am Yuanchu Liang based in Australia, Canberra. I am doing a computer science PhD, supervised by Prof. Hanna Kurniawati, at the Robust Decision Making and Learning Lab, The Australian National Univeristy.
  
  My research direction focuses on building robust general purpose sequential decision making systems with application in robotics. It is my hope to see robots become an essential ingredient in our daily life in the near future, just like smart phones today. To achieve this, today's roboot need to be able to handle uncertainties from the real world and learn useful patterns from its surroundings.
  
  In particular, I look into the Partially Observable Markov Decision Process (POMDP) and see how to scale its solutions method for Robotics motion planning under uncertainties. 
  I investigate in sample efficient reinforcement learning algorithms that smartly collects data and extract statistical patterns to inform deicision makings. 
  Being able to transfer existing knowledge to a similar domain is yet another way to reduce training resources. 
  And lastly, I am interesting in considering partially observable settings in reinforcement learning to allivate the learner's brittleness in the face of uncertainties.

  Outside of work, I love meeting new people, sharing new ideas, reading books and do many outdoor activities. I am a serious rock climbing enthusiast, and this hobby has became my way of meditation. 

content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Australian National University
        caption: 2019 - 2023
        sub_title: Double Degrees in Bachelor of Engineering (First Class Honours) and Bachelor of Science.
        description: | # this will include new lines to allow paragraphs
          The flexibility offered by ANU allows me to do a double degree in Enginnering and Science. 
          
          I specialised in mechatronics engineering and explored areas like control theory, system dynamics, embedded systems and robotics. 
          
          Under my science degree, I studied computer science with a focus on AI and ML, and mathematics including analysis, algebra and numerical methods.

          During these 5 years, I had many opportunies to conduct research and join practical student projects. Looking back, I am grateful for having such an intense but execiting learning journey. 


  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Scaling Long-Horizon Online POMDP Planning via Rapid State Space Sampling
        link: [Paper Link](https://arxiv.org/abs/2411.07032)
        # link_text: Project Website
        # additional_links:
        #   - title:  ROP-RAS3
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This is my first PhD project. I am lucky enough to collabote with Lydia Kavraki's lab and we proposed a novel algorithm that leverage fast motion planning library (VAMP) and the reference-based POMDP to handle online POMDP planning with long horizons. Empirically, we test on many robotic problems and our method outperforms the state-of-the-art methods by multiple factors.

      - layout: top-middle
        title: Recurrent Macro Actions Generator for POMDP Planning
        link: https://ieeexplore.ieee.org/abstract/document/10341759?casa_token=y3mzX6uneXcAAAAA:j1z44RjTuBVlwqLZPj39g4tGr-kxfx5KJE9yJniQ4hPNtEi4KhHuTsojb4S8KlmJS7fjOH2LF3Lp
        additional_links:
          - title:  RMAG
            icon: fab fa-github
            url: https://github.com/YC-Liang/Recurrent-Macro-Action-Generator
        description: |
          This is my fourth year undergraduate work that focuses on using recurrent neural networks to handle memories in the form of histories in POMDPs to learn to generate macro actions for POMDP planning. The new architecture boosts the state-of-the-art MAGIC across all tested benchmarks.

      - layout: top-middle
        title: DRT A Lightweight Single Image Deraining Recursive Transformer
        link: https://openaccess.thecvf.com/content/CVPR2022W/NTIRE/html/Liang_DRT_A_Lightweight_Single_Image_Deraining_Recursive_Transformer_CVPRW_2022_paper.html
        additional_links:
          - title:  DRT
            icon: fab fa-github
            url: https://github.com/YC-Liang/DRT
        description:
          This is my third year undergraduate work on designing efficient nerual network architecture for single image deraining. In particular, we recursively define transformer blocks to reuse weights to boost performance while keeping memory usages low. The performance has surpassed many big models across different data sets.

  - title: Other Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Summer Research Scholarships
        # link_text: boringcompany.com
        sub_title: Online Attention in Social Media
        caption: Nov 2021 - Feb 2022
        description: | # this will include new lines to allow paragraphs
            I worked with Prof. Lexing Xie on online attention markets and the effects of filter bubbles and echo chamber effects in social media. We investigated in different stochastic models to simulate the online interaction process and used the T-Recs simulator to perform experiments.

      - layout: left
        title: CSIRO Student Internships
        link_text: https://www.csiro.au/en/
        caption: Nov 2022 - Mar 2023
        description: |
            During the last year of my undergraduate, I worked under Dr Tirthankar Bandyopadhyay at CSIRO and built a simulation environment for robotic arms to interact with cluttered objects. Specifically, I used the Mujoco physics engine and OMPL library to achieve the goal.
          
  - title: A Little More About Me
    layout: top-middle
    content: | # this will include new lines to allow paragraphs
      Our lab group
      ![RDL Lab](/images/lab.JPG "RDL Lab")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
